"""initial schema

Revision ID: e3da64a5cad3
Revises: 
Create Date: 2026-08-31 20:55:11.353797
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3da64a5cad3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('region', sa.String(length=96), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('complaint_portal_url', sa.String(length=512), nullable=True),
    sa.Column('avg_response_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplaces'))
    )
    op.create_index(op.f('ix_marketplaces_code'), 'marketplaces', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('requires_vendor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=191), nullable=True),
    sa.Column('contact_email', sa.String(length=191), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=96), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('sla_policy_id', sa.Integer(), nullable=True),
    sa.Column('autonomy_tier', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_contact_email'), 'vendors', ['contact_email'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    op.create_index(op.f('ix_vendors_sla_policy_id'), 'vendors', ['sla_policy_id'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('marketplace_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('seller_name', sa.String(length=191), nullable=True),
    sa.Column('seller_url', sa.String(length=1024), nullable=True),
    sa.Column('seller_country', sa.String(length=96), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('listing_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('captured_data', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_listings_marketplace_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_listings_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings'))
    )
    op.create_index(op.f('ix_listings_case_id'), 'listings', ['case_id'], unique=False)
    op.create_index(op.f('ix_listings_marketplace_id'), 'listings', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_listings_seller_name'), 'listings', ['seller_name'], unique=False)
    op.create_index(op.f('ix_listings_vendor_id'), 'listings', ['vendor_id'], unique=False)
    op.create_index('ix_listings_vendor_marketplace', 'listings', ['vendor_id', 'marketplace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=96), nullable=False),
    sa.Column('last_name', sa.String(length=96), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_users_vendor_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_vendor_id'), 'users', ['vendor_id'], unique=False)
    op.create_index('ix_users_vendor_status', 'users', ['vendor_id', 'status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=191), nullable=True),
    sa.Column('role_code', sa.String(length=64), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=191), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('object_label', sa.String(length=512), nullable=True),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_audit_logs_vendor_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_action_ts', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_vendor_id'), 'audit_logs', ['vendor_id'], unique=False)
    op.create_index('ix_audit_object', 'audit_logs', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_audit_vendor_ts', 'audit_logs', ['vendor_id', 'timestamp'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=191), nullable=True),
    sa.Column('trademark', sa.String(length=191), nullable=True),
    sa.Column('trademark_registration', sa.String(length=128), nullable=True),
    sa.Column('product_url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('msrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_products_created_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_products_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_vendor_id'), 'products', ['vendor_id'], unique=False)
    op.create_index('ix_products_vendor_sku', 'products', ['vendor_id', 'sku'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('response_hours', sa.Integer(), nullable=False),
    sa.Column('resolution_hours', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('at_risk_percent', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sla_policies_created_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_sla_policies_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_policies'))
    )
    op.create_index(op.f('ix_sla_policies_name'), 'sla_policies', ['name'], unique=False)
    op.create_index(op.f('ix_sla_policies_vendor_id'), 'sla_policies', ['vendor_id'], unique=False)
    op.create_table('user_vendor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_user_vendor_assignments_assigned_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_vendor_assignments_user_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_user_vendor_assignments_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_vendor_assignments')),
    sa.UniqueConstraint('user_id', 'vendor_id', name='uq_user_vendor')
    )
    op.create_index(op.f('ix_user_vendor_assignments_user_id'), 'user_vendor_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_vendor_assignments_vendor_id'), 'user_vendor_assignments', ['vendor_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('marketplace_id', sa.Integer(), nullable=True),
    sa.Column('infringement_type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=64), nullable=True),
    sa.Column('analysis_started_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(), nullable=True),
    sa.Column('autonomy_tier', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('sla_policy_id', sa.Integer(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('sla_state', sa.String(length=32), nullable=False),
    sa.Column('sla_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_cases_approved_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_cases_assigned_to_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_cases_created_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_cases_listing_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_cases_marketplace_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cases_product_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], name=op.f('fk_cases_sla_policy_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_cases_vendor_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index(op.f('ix_cases_ai_confidence'), 'cases', ['ai_confidence'], unique=False)
    op.create_index(op.f('ix_cases_assigned_to_id'), 'cases', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_created_by_id'), 'cases', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_cases_infringement_type'), 'cases', ['infringement_type'], unique=False)
    op.create_index(op.f('ix_cases_listing_id'), 'cases', ['listing_id'], unique=False)
    op.create_index(op.f('ix_cases_marketplace_id'), 'cases', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_cases_priority'), 'cases', ['priority'], unique=False)
    op.create_index(op.f('ix_cases_product_id'), 'cases', ['product_id'], unique=False)
    op.create_index(op.f('ix_cases_recommended_action'), 'cases', ['recommended_action'], unique=False)
    op.create_index(op.f('ix_cases_risk_level'), 'cases', ['risk_level'], unique=False)
    op.create_index('ix_cases_sla', 'cases', ['sla_state', 'sla_deadline'], unique=False)
    op.create_index(op.f('ix_cases_sla_deadline'), 'cases', ['sla_deadline'], unique=False)
    op.create_index(op.f('ix_cases_sla_state'), 'cases', ['sla_state'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index('ix_cases_vendor_created', 'cases', ['vendor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_cases_vendor_id'), 'cases', ['vendor_id'], unique=False)
    op.create_index('ix_cases_vendor_status', 'cases', ['vendor_id', 'status'], unique=False)
    op.create_table('ai_agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_ai_agent_runs_case_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_ai_agent_runs_triggered_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_ai_agent_runs_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_agent_runs'))
    )
    op.create_index('ix_agent_runs_agent_started', 'ai_agent_runs', ['agent_name', 'started_at'], unique=False)
    op.create_index('ix_agent_runs_case_seq', 'ai_agent_runs', ['case_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_agent_name'), 'ai_agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_case_id'), 'ai_agent_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_correlation_id'), 'ai_agent_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_started_at'), 'ai_agent_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_status'), 'ai_agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_vendor_id'), 'ai_agent_runs', ['vendor_id'], unique=False)
    op.create_table('case_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_case_assignments_assigned_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_assignments_case_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_case_assignments_user_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_case_assignments_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_assignments'))
    )
    op.create_index(op.f('ix_case_assignments_case_id'), 'case_assignments', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_assignments_user_id'), 'case_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_case_assignments_vendor_id'), 'case_assignments', ['vendor_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_notifications_case_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_notifications_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_case_id'), 'notifications', ['case_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_vendor_id'), 'notifications', ['vendor_id'], unique=False)
    op.create_table('ai_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['ai_agent_runs.id'], name=op.f('fk_ai_findings_agent_run_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_ai_findings_case_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_ai_findings_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_findings'))
    )
    op.create_index(op.f('ix_ai_findings_agent_run_id'), 'ai_findings', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_ai_findings_case_id'), 'ai_findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_ai_findings_kind'), 'ai_findings', ['kind'], unique=False)
    op.create_index(op.f('ix_ai_findings_vendor_id'), 'ai_findings', ['vendor_id'], unique=False)
    op.create_index('ix_findings_case_kind', 'ai_findings', ['case_id', 'kind'], unique=False)
    op.create_table('enforcement_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('recommended_by_run_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_version', sa.Integer(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('notice_draft', sa.Text(), nullable=True),
    sa.Column('evidence_package', sa.JSON(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submission_reference', sa.String(length=191), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('sla_state', sa.String(length=32), nullable=False),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('marketplace_response', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('is_escalated', sa.Boolean(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_enforcement_actions_case_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_enforcement_actions_created_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommended_by_run_id'], ['ai_agent_runs.id'], name=op.f('fk_enforcement_actions_recommended_by_run_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_enforcement_actions_submitted_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_enforcement_actions_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enforcement_actions'))
    )
    op.create_index(op.f('ix_enforcement_actions_action_type'), 'enforcement_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_approval_id'), 'enforcement_actions', ['approval_id'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_case_id'), 'enforcement_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_reference'), 'enforcement_actions', ['reference'], unique=True)
    op.create_index(op.f('ix_enforcement_actions_result'), 'enforcement_actions', ['result'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_sla_deadline'), 'enforcement_actions', ['sla_deadline'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_status'), 'enforcement_actions', ['status'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_submitted_at'), 'enforcement_actions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_vendor_id'), 'enforcement_actions', ['vendor_id'], unique=False)
    op.create_index('ix_enforcement_vendor_status', 'enforcement_actions', ['vendor_id', 'status'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=191), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.String(length=96), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('related_agent', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('relevance', sa.String(length=32), nullable=False),
    sa.Column('relevance_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_reason', sa.String(length=512), nullable=True),
    sa.Column('archived_by_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['ai_agent_runs.id'], name=op.f('fk_evidence_agent_run_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['archived_by_id'], ['users.id'], name=op.f('fk_evidence_archived_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_evidence_case_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_evidence_reviewed_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_evidence_uploaded_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_evidence_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_agent_run_id'), 'evidence', ['agent_run_id'], unique=False)
    op.create_index('ix_evidence_case_category', 'evidence', ['case_id', 'category'], unique=False)
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_category'), 'evidence', ['category'], unique=False)
    op.create_index(op.f('ix_evidence_checksum'), 'evidence', ['checksum'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_ref'), 'evidence', ['evidence_ref'], unique=True)
    op.create_index(op.f('ix_evidence_relevance'), 'evidence', ['relevance'], unique=False)
    op.create_index(op.f('ix_evidence_vendor_id'), 'evidence', ['vendor_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('enforcement_action_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=False),
    sa.Column('decided_by_email', sa.String(length=191), nullable=False),
    sa.Column('decided_by_role', sa.String(length=64), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.String(length=64), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_risk_level', sa.String(length=32), nullable=True),
    sa.Column('recommendation_version', sa.Integer(), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=True),
    sa.Column('autonomy_tier', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_approvals_case_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_approvals_decided_by_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enforcement_action_id'], ['enforcement_actions.id'], name=op.f('fk_approvals_enforcement_action_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_approvals_vendor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index('ix_approvals_case_created', 'approvals', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_approvals_case_id'), 'approvals', ['case_id'], unique=False)
    op.create_index(op.f('ix_approvals_decided_by_id'), 'approvals', ['decided_by_id'], unique=False)
    op.create_index(op.f('ix_approvals_decision'), 'approvals', ['decision'], unique=False)
    op.create_index(op.f('ix_approvals_enforcement_action_id'), 'approvals', ['enforcement_action_id'], unique=False)
    op.create_index(op.f('ix_approvals_vendor_id'), 'approvals', ['vendor_id'], unique=False)

    # --- circular foreign keys ---------------------------------------
    # These four pairs reference each other, so they cannot be declared
    # inline. They are added once every table exists.
    op.create_foreign_key(
        'fk_vendors_sla_policy_id', 'vendors', 'sla_policies',
        ['sla_policy_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_vendors_created_by_id', 'vendors', 'users',
        ['created_by_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_listings_case_id', 'listings', 'cases',
        ['case_id'], ['id'], ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_enforcement_actions_approval_id', 'enforcement_actions', 'approvals',
        ['approval_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the whole schema.

    Written by hand rather than autogenerated: MySQL refuses to drop an
    index that a foreign key still needs, so the circular constraints come
    off first and the tables are then dropped child-first. Dropping a table
    removes its own indexes, so no explicit drop_index calls are needed.
    """
    op.drop_constraint('fk_vendors_sla_policy_id', 'vendors', type_='foreignkey')
    op.drop_constraint('fk_vendors_created_by_id', 'vendors', type_='foreignkey')
    op.drop_constraint('fk_listings_case_id', 'listings', type_='foreignkey')
    op.drop_constraint('fk_enforcement_actions_approval_id', 'enforcement_actions', type_='foreignkey')

    op.drop_table('notifications')
    op.drop_table('audit_logs')
    op.drop_table('ai_findings')
    op.drop_table('evidence')
    op.drop_table('approvals')
    op.drop_table('enforcement_actions')
    op.drop_table('ai_agent_runs')
    op.drop_table('case_assignments')
    op.drop_table('cases')
    op.drop_table('listings')
    op.drop_table('products')
    op.drop_table('user_vendor_assignments')
    op.drop_table('sla_policies')
    op.drop_table('users')
    op.drop_table('vendors')
    op.drop_table('marketplaces')
    op.drop_table('roles')
